version: "3"
services:

  php:
    image: wodby/php:${PHP_VERSION}
    environment:
      PHP_FPM_CLEAR_ENV: "yes"
      PHP_XDEBUG:
      PHP_XDEBUG_MODE: "develop,debug"
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_IDE_CONFIG: "serverName=a11y"
    volumes:
      - ./:/var/www/html

  web:
    image: wodby/nginx:latest
    depends_on:
      - php
    environment:
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
    volumes:
      - ./html/:/var/www/html
    ports:
      - "80:80"

  selenium:
    image: selenium/standalone-chrome:4.5.0
    shm_size: 2gb
    environment:
      - DISPLAY=:99
      - VNC_NO_PASSWORD=1
    ports:
      - '7900:7900'
